version: 2
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - restore_cache:
          keys:
            - haskell-stack-{{ checksum "oidc-client.cabal" }}
      - run:
          command: stack setup
      - run:
          command: stack test --pedantic
      - save_cache:
          key: haskell-stack-{{ checksum "oidc-client.cabal" }}
          paths:
            - ".stack-work"
            - "/root/.stack"
